plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    runs.configureEach {
        vmArg("-Dlibrarianlib.logging.debug=hooked")
    }
}

configurations {
    create("modJar")

    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation libs.platform.fabricLoader
    modImplementation libs.platform.fabricApi
    modImplementation libs.platform.mods.fabricLanguageKotlin
    modImplementation libs.platform.mods.architecturyFabric

    modCompileOnly libs.mods.iris

    modImplementation libs.bundles.mods.liblib.fabric

    modImplementation libs.mods.trinkets
    modImplementation libs.mods.cardinalComponents.base
    modImplementation libs.mods.cardinalComponents.entity
    include libs.mods.cardinalComponents.base
    include libs.mods.cardinalComponents.entity
    modApi libs.mods.sableCompanionFabric
    include libs.mods.sableCompanionFabric

    modApi libs.runtime.mods.sableFabric

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

tasks.register("downloadModJars", Sync.class) {
    from(configurations.modJar)
    into("${project.projectDir}/run/mods")
}

def expansions = [
        version: project.version,
        dep_minecraft: project.property('fabric.mod_deps.minecraft'),
        dep_fabric_api: project.property('fabric.mod_deps.fabric_api'),
        dep_fabric_language_kotlin: project.property('fabric.mod_deps.fabric_language_kotlin'),
        dep_architectury: project.property('fabric.mod_deps.architectury'),
        dep_trinkets: project.property('fabric.mod_deps.trinkets'),
        dep_liblib: project.property('fabric.mod_deps.liblib'),
]
processResources {
    inputs.properties(expansions)
    dependsOn(tasks.downloadModJars)

    filesMatching('fabric.mod.json') {
        expand(expansions)
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
