plugins {
    id 'fabric-loom' version '1.9.2'
    id 'maven-publish'
    id 'eclipse'
    id 'idea'
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.1.0'
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = project.archivesBaseName
version = project.mod_version
group = 'com.teamwizardry.wizardry'

repositories {
    mavenCentral()
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = "https://maven.ladysnake.org/releases"
    }
    maven { url = "https://s01.oss.sonatype.org/content/repositories/snapshots" }
    maven { url = "https://cursemaven.com" }
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "curse.maven:irisshaders-455508:6213635" // Iris v1.8.8

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
    modImplementation "dev.emi:trinkets:${project.trinkets_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}"

    [
            "com.teamwizardry.librarianlib:mosaic:${liblib_version}",
            "com.teamwizardry.librarianlib:glitter:${liblib_version}",
            "com.teamwizardry.librarianlib:etcetera:${liblib_version}"
    ].each {
        modImplementation(it)
    }
}

loom {
    mixin.defaultRefmapName.set("hooked.refmap.json")

    runConfigs.configureEach {
        vmArg("-javaagent:$buildDir/agent/mixin.jar")
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    it.kotlinOptions {
        jvmTarget = 21
        javaParameters = true
        freeCompilerArgs = ['-Xjvm-default=enable']
    }
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(remapJar) {
                builtBy remapJar
            }
            artifact(sourcesJar) {
                builtBy remapSourcesJar
            }
        }
    }

    repositories {

    }
}

tasks.register("copyMixinAgent", Sync) {
    from(configurations.runtimeClasspath)
    include("sponge-mixin-*")
    into(file("$buildDir/agent"))
    eachFile {
        name = "mixin.jar"
    }
}

processResources {
    dependsOn(copyMixinAgent)
}
