import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.6' apply false

    id 'org.jetbrains.kotlin.jvm' version '2.0.21' apply false
    id 'com.google.devtools.ksp' version '2.0.21-1.0.28' apply false
}

architectury {
    minecraft = project.minecraft_version
    compileOnly()
}

allprojects {
    group = project.maven_group
    version = project.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'

    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'com.google.devtools.ksp'

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$project.archives_name-$project.name"
    }

    repositories {
        mavenCentral()
        maven { url = "https://maven.terraformersmc.com/" }
        maven { url = "https://maven.ladysnake.org/releases" }
        maven { url = "https://s01.oss.sonatype.org/content/repositories/snapshots" }
        maven { url = "https://cursemaven.com" }
        maven { url = 'https://thedarkcolour.github.io/KotlinForForge/' }
        maven { url = "https://maven.theillusivec4.top/" } // curios
        mavenLocal()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$project.minecraft_version"
        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$project.yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$project.yarn_mappings_patch_neoforge_version")
        }

        ksp "dev.zacsweers.autoservice:auto-service-ksp:1.2.0"
        implementation "com.google.auto.service:auto-service-annotations:1.1.0"
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    tasks.withType(KotlinCompile.class).configureEach {
        compilerOptions {
            languageVersion = KotlinVersion.KOTLIN_2_0
            apiVersion = KotlinVersion.KOTLIN_2_0

            jvmTarget = JvmTarget.JVM_21
            javaParameters = true
            optIn.addAll(
                    "kotlin.ExperimentalStdlibApi",
                    "kotlin.ExperimentalUnsignedTypes",
                    "kotlin.contracts.ExperimentalContracts",
            )
            freeCompilerArgs.addAll(
                    "-Xjvm-default=all"
            )
        }
    }

    ksp {
        useKsp2 = true
    }
}
