org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

mod_version=2.0.0-alpha.5
archivesBaseName=hooked
release.curseforge.type=alpha
release.modrinth.type=ALPHA

fabric_version=0.115.3+1.21.1
fabric_kotlin_version=1.13.1+kotlin.2.1.10
liblib_version=5.0.0-alpha.13
trinkets_version=3.10.0
cardinal_components_version=6.1.2

mod.dependencies.fabricapi=>=0.115.3+1.21.1
mod.dependencies.fabricloader=>=0.16.10
mod.dependencies.minecraft=1.21.x
mod.dependencies.flk=>=1.13.1+kotlin.2.1.10
mod.dependencies.trinkets=>=3.10.0

mod.modmenu.hooked_name=Hooked