org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3

mod_version=2.0.0-alpha.7
maven_group = dev.thecodewarrior.hooked
archives_name = hooked
enabled_platforms = fabric,neoforge

architectury_api_version = 13.0.8
fabric_loader_version = 0.16.14
fabric_api_version=0.115.3+1.21.1
neoforge_version = 21.1.172
yarn_mappings_patch_neoforge_version = 1.21+build.4

fabric_kotlin_version=1.12.3+kotlin.2.0.21
liblib_version=5.0.0-alpha.14
trinkets_version=3.10.0
cardinal_components_version=6.1.2

kotlin_for_forge_version=5.4.0
# at the moment we use a custom Curios jar which has the `remap = false` flags removed
# so updating this won't change the jar
curios_version=9.5.1+1.21.1

release.curseforge.type=alpha
release.modrinth.type=ALPHA

mod.dependencies.fabricapi=>=0.115.3+1.21.1
mod.dependencies.fabricloader=>=0.16.10
mod.dependencies.minecraft=1.21.x
mod.dependencies.flk=>=1.12.3+kotlin.2.0.21
mod.dependencies.trinkets=>=3.10.0

mod.modmenu.hooked_name=Hooked