org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
yarn_mappings_patch_neoforge_version = 1.21+build.4

mod_version=2.0.3
maven_group = dev.thecodewarrior.hooked
archives_name = hooked
enabled_platforms = fabric,neoforge

# maven dependency versions
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.14
fabric_api_version = 0.115.3+1.21.1
neoforge_version = 21.1.172

fabric_kotlin_version=1.12.3+kotlin.2.0.21
liblib_version=5.0.0
trinkets_version=3.10.0
cardinal_components_version=6.1.2

kotlin_for_forge_version=5.4.0
# at the moment we use a custom Curios jar which has the `remap = false` flags removed
# so updating this won't change the jar
curios_version=9.5.1+1.21.1

neoforge.mod_deps.neoforge = [21.1,)
neoforge.mod_deps.minecraft = [1.21.1,)
neoforge.mod_deps.kotlinforforge = [5.4.0,)
neoforge.mod_deps.architectury = [13.0.8,)
neoforge.mod_deps.curios = [9.5.1+1.21.1,)
neoforge.mod_deps.liblib = [5.0.0,)

fabric.mod_deps.minecraft = ~1.21.1
fabric.mod_deps.fabric_api = >=0.115.3+1.21.1
fabric.mod_deps.fabric_language_kotlin = >=1.12.3+kotlin.2.0.21
fabric.mod_deps.architectury = >=13.0.8
fabric.mod_deps.trinkets = >=3.10.0
fabric.mod_deps.liblib = >=5.0.0
