architectury {
    common project.enabled_platforms.split(',')
}

// the run configs hard-code the `build/devlibs/...-dev.jar` path, which includes the project version.
// (see `fabric/.gradle/architectury/.properties`)
// This file is only re-generated when closing and opening the project, so bumping the version breaks builds.
project.version = "0.0.0"

dependencies {
    modImplementation libs.platform.mods.architecturyApi

    modCompileOnly libs.bundles.mods.liblib.common

    modCompileOnly libs.mods.sableCompanionFabric
    modCompileOnly libs.mods.sableFabric
}
