architectury {
    common project.enabled_platforms.split(',')
}

dependencies {
    modImplementation "dev.architectury:architectury:$project.architectury_api_version"

    modCompileOnly "com.teamwizardry.librarianlib:mosaic:${liblib_version}"
    modCompileOnly "com.teamwizardry.librarianlib:glitter:${liblib_version}"
    modCompileOnly "com.teamwizardry.librarianlib:etcetera:${liblib_version}"
}
