modLoader="javafml"
loaderVersion="[1,)"

license="BSD 2-Clause"
issueTrackerURL="https://github.com/thecodewarrior/Hooked/issues"

[[mods]]
modId="hooked"
version="${version}"
displayName="Hooked"
logoFile="hooked_logo.png"
credits="Much thanks to QuickHull3d"
authors="thecodewarrior"
description='''
Hooked: Grappling hooks done simple, natural, and useful.
'''

[[mixins]]
config = "hooked.mixins.json"

[[dependencies.hooked]]
modId = "neoforge"
type = "required"
versionRange = "${dep_neoforge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.hooked]]
modId = "minecraft"
type = "required"
versionRange = "${dep_minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.hooked]]
modId="kotlinforforge"
mandatory=true
versionRange="${dep_kotlinforforge}"
ordering="NONE"
side="BOTH"

[[dependencies.hooked]]
modId = "architectury"
type = "required"
versionRange = "${dep_architectury}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hooked]]
modId="curios"
mandatory=true
versionRange="${dep_curios}"
ordering="NONE"
side="BOTH"

[[dependencies.hooked]]
modId="liblib_mosaic"
mandatory=true
versionRange="${dep_liblib}"
ordering="NONE"
side="BOTH"

[[dependencies.hooked]]
modId="liblib_glitter"
mandatory=true
versionRange="${dep_liblib}"
ordering="NONE"
side="BOTH"

[[dependencies.hooked]]
modId="liblib_etcetera"
mandatory=true
versionRange="${dep_liblib}"
ordering="NONE"
side="BOTH"
