plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$project.neoforge_version"

    modImplementation "dev.architectury:architectury-neoforge:$project.architectury_api_version"

    implementation("thedarkcolour:kotlinforforge-neoforge:$project.kotlin_for_forge_version") {
        exclude(group: "net.neoforged")
        exclude(group: "net.neoforged.fancymodloader")
    }

    modImplementation "com.teamwizardry.librarianlib:mosaic-neoforge:${liblib_version}"
    modImplementation "com.teamwizardry.librarianlib:glitter-neoforge:${liblib_version}"
    modImplementation "com.teamwizardry.librarianlib:etcetera-neoforge:${liblib_version}"

    // We need this because curios adds `remap = false` to its mixin annotations, which means architectury (rightly)
    // won't remap them to yarn mappings. I built a custom jar with that flag removed, and it works.
    modImplementation files("curios-neoforge-9.5.1+1.21.1.jar")
    //modCompileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    //modRuntimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    inputs.property 'version', project.version

    // minecraft won't load recipes from the common module
    from(project(":common").files("src/main/resources/data")) {
        into("data")
    }

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
